"""Type stubs for the native Rust extension module."""

from typing import Any

# --- Exception classes ---

class PaperJamError(Exception): ...
class ParseError(PaperJamError): ...
class PasswordRequired(PaperJamError): ...  # noqa: N818
class InvalidPassword(PaperJamError): ...  # noqa: N818
class PageOutOfRange(PaperJamError): ...  # noqa: N818
class UnsupportedFeature(PaperJamError): ...  # noqa: N818
class TableExtractionError(PaperJamError): ...

# --- Classes ---

class RustDocument:
    @staticmethod
    def open(path: str) -> RustDocument: ...
    @staticmethod
    def open_with_password(path: str, password: str) -> RustDocument: ...
    @staticmethod
    def from_bytes(data: bytes) -> RustDocument: ...
    @staticmethod
    def from_bytes_with_password(data: bytes, password: str) -> RustDocument: ...
    def page_count(self) -> int: ...
    def page(self, number: int) -> RustPage: ...
    def metadata(self) -> dict[str, Any]: ...
    def save_bytes(self) -> bytes: ...
    def save(self, path: str) -> None: ...
    def extract_images(self, page_number: int) -> list[dict[str, Any]]: ...
    def bookmarks(self) -> list[dict[str, Any]]: ...

class RustPage:
    def number(self) -> int: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def rotation(self) -> int: ...
    def extract_text(self) -> str: ...
    def extract_text_spans(self) -> list[dict[str, Any]]: ...
    def extract_text_lines(self) -> list[dict[str, Any]]: ...
    def extract_tables(
        self,
        *,
        strategy: str = "auto",
        min_rows: int = 2,
        min_cols: int = 2,
        snap_tolerance: float = 3.0,
        row_tolerance: float = 0.5,
        min_col_gap: float = 10.0,
    ) -> list[dict[str, Any]]: ...

# --- Module-level functions ---

def merge(
    documents: list[RustDocument],
    deduplicate_resources: bool = False,
) -> RustDocument: ...

def split(
    document: RustDocument,
    ranges: list[tuple[int, int]],
) -> list[RustDocument]: ...

def rotate_pages(
    document: RustDocument,
    page_rotations: list[tuple[int, int]],
) -> RustDocument: ...

def reorder_pages(
    document: RustDocument,
    page_order: list[int],
) -> RustDocument: ...
