rust:
  - changed-files:
      - any-glob-to-any-file:
          - 'crates/**'
          - '**/*.rs'
          - 'Cargo.toml'
          - 'Cargo.lock'

python:
  - changed-files:
      - any-glob-to-any-file:
          - 'paperjam/**'
          - 'mcp-server/**'
          - '**/*.py'
          - 'pyproject.toml'

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*.js'
          - 'docs/**/*.jsx'
          - 'docs/**/*.ts'
          - 'docs/**/*.tsx'
          - 'docs/**/*.mjs'
          - 'docs/**/*.cjs'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '**/*.md'
          - 'README*'

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/actions/**'

mcp:
  - changed-files:
      - any-glob-to-any-file:
          - 'crates/paperjam-mcp/**'
          - 'mcp-server/**'

wasm:
  - changed-files:
      - any-glob-to-any-file:
          - 'crates/paperjam-wasm/**'
