"""paperjam -- Fast document processing powered by Rust."""

from __future__ import annotations

__version__ = "0.1.0"

from paperjam._any_document import AnyDocument
from paperjam._async import (
    amerge,
    aopen,
    arender,
    ato_markdown,
)
from paperjam._convert import convert, convert_bytes, detect_format
from paperjam._document import Document
from paperjam._enums import (
    AnnotationType,
    DocumentFormat,
    FormFieldType,
    ImageFormat,
    Rotation,
    TableStrategy,
    WatermarkLayer,
    WatermarkPosition,
)
from paperjam._functions import diff, merge, merge_files, open, open_pdf, to_markdown
from paperjam._page import Page
from paperjam._paperjam import (
    AnnotationError,
    EncryptionError,
    FormatError,
    FormError,
    InvalidPassword,
    OptimizationError,
    PageOutOfRange,
    ParseError,
    PasswordRequired,
    PipelineError,
    RedactError,
    RenderError,
    SanitizeError,
    SignatureError,
    TableExtractionError,
    UnsupportedFeature,
    WatermarkError,
)
from paperjam._paperjam import (
    PaperJamError as PdfError,
)
from paperjam._pipeline import run_pipeline, validate_pipeline
from paperjam._render import render
from paperjam._types import (
    Annotation,
    Bookmark,
    Cell,
    CertificateInfo,
    ChoiceOption,
    ContentBlock,
    ConversionAction,
    ConversionResult,
    CreateFieldResult,
    DiffOp,
    DiffResult,
    DiffSummary,
    EncryptResult,
    FillFormResult,
    FormField,
    Image,
    LayoutRegion,
    Link,
    Metadata,
    ModifyFieldResult,
    OptimizeResult,
    PageDiff,
    PageInfo,
    PageLayout,
    PdfUaReport,
    Permissions,
    RedactedItem,
    RedactRegion,
    RedactResult,
    RenderedImage,
    Row,
    SanitizedItem,
    SanitizeResult,
    SearchResult,
    SignatureInfo,
    SignatureValidity,
    Table,
    TextLine,
    TextSpan,
    ValidationIssue,
    ValidationReport,
    VisualDiffPage,
    VisualDiffResult,
)

__all__ = [
    "Annotation",
    "AnnotationError",
    "AnnotationType",
    "AnyDocument",
    "Bookmark",
    "Cell",
    "CertificateInfo",
    "ChoiceOption",
    "ContentBlock",
    "ConversionAction",
    "ConversionResult",
    "CreateFieldResult",
    "DiffOp",
    "DiffResult",
    "DiffSummary",
    "Document",
    "DocumentFormat",
    "EncryptResult",
    "EncryptionError",
    "FillFormResult",
    "FormError",
    "FormField",
    "FormFieldType",
    "FormatError",
    "Image",
    "ImageFormat",
    "InvalidPassword",
    "LayoutRegion",
    "Link",
    "Metadata",
    "ModifyFieldResult",
    "OptimizationError",
    "OptimizeResult",
    "Page",
    "PageDiff",
    "PageInfo",
    "PageLayout",
    "PageOutOfRange",
    "ParseError",
    "PasswordRequired",
    "PdfError",
    "PdfUaReport",
    "Permissions",
    "PipelineError",
    "RedactError",
    "RedactRegion",
    "RedactResult",
    "RedactedItem",
    "RenderError",
    "RenderedImage",
    "Rotation",
    "Row",
    "SanitizeError",
    "SanitizeResult",
    "SanitizedItem",
    "SearchResult",
    "SignatureError",
    "SignatureInfo",
    "SignatureValidity",
    "Table",
    "TableExtractionError",
    "TableStrategy",
    "TextLine",
    "TextSpan",
    "UnsupportedFeature",
    "ValidationIssue",
    "ValidationReport",
    "VisualDiffPage",
    "VisualDiffResult",
    "WatermarkError",
    "WatermarkLayer",
    "WatermarkPosition",
    "amerge",
    "aopen",
    "arender",
    "ato_markdown",
    "convert",
    "convert_bytes",
    "detect_format",
    "diff",
    "merge",
    "merge_files",
    "open",
    "open_pdf",
    "render",
    "run_pipeline",
    "to_markdown",
    "validate_pipeline",
]
