pub mod annotate;
pub mod bookmarks;
pub mod conversion;
pub mod diff;
pub mod forms;
pub mod merge;
pub mod metadata;
pub mod optimize;
pub mod render;
pub mod security;
pub mod signature;
pub mod stamp;
pub mod toc;
pub mod transform;
pub mod validation;
pub mod visual_diff;
pub mod watermark;

pub use annotate::{py_add_annotation, py_remove_annotations};
pub use bookmarks::py_set_bookmarks;
pub use conversion::py_convert_to_pdf_a;
pub use diff::py_diff_documents;
pub use forms::{py_add_form_field, py_fill_form, py_modify_form_field};
pub use merge::{py_merge, py_split};
pub use metadata::py_set_metadata;
pub use optimize::py_optimize;
pub use render::{py_render_file, py_render_page, py_render_pages, py_render_pages_bytes};
pub use security::{py_encrypt, py_redact, py_redact_text, py_sanitize};
pub use signature::{py_extract_signatures, py_sign_document, py_verify_signatures};
pub use stamp::py_stamp_pages;
pub use toc::py_generate_toc;
pub use transform::{py_delete_pages, py_insert_blank_pages, py_reorder_pages, py_rotate_pages};
pub use validation::{py_validate_pdf_a, py_validate_pdf_ua};
pub use visual_diff::py_visual_diff;
pub use watermark::py_add_watermark;
